name: auto-release

on:
  pull_request:
    types: [closed]


jobs:
  publish:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: pnpm install

      - run: pnpm run '/build:*/'

      - run: pnpm publish --no-git-checks --filter @liweijie0812/tdesign-auto-import-resolver --tag alpha
      - uses: TDesignOteam/flow-pilot-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          packages: 'tdesign-vue-next,@tdesign-vue-next/chat,@liweijie0812/tdesign-auto-import-resolver'
